### ISSUE TITLE
Options is not working properly

### ISSUE THREAD

**Issue by JMZ10** [DarkoPendragon/discord.js-musicbot-addon#100]
**Describe the bug**
Supplied config is not applying.

**To Reproduce**
Start the bot as you normally would and try set any option to  something other than default. In my screenshot I use maxQueueSize and try to queue bigger than 50 (300).

**Expected behavior**
IF you set a config option correctly, it will operate based on that value. (eg. maxQueueSize 300 allows 300 queued songs and doesn't  fall back to default).

**Screenshots**
![image](https://user-images.githubusercontent.com/11156463/57172748-93b04380-6e67-11e9-9f94-5ea83449b506.png)

**Versions**
- OS version Windows 10 Pro Build 17763
- Module version 13.5.1
- Discord.js version 11.4.2
- Node.js version 10.15.3

**Additional context**
The exception here is that the YT key obviously works, but that seems to be it.

**Comment by DarkoPendragon** [comment]
[This only happens with playlists](https://github.com/DarkoPendragon/discord.js-musicbot-addon/blob/2f1f4f87aefe2392d0ac86d728d9bca1bea4d219/index.js#L433). The maxQueue setting will only limit a playlist when it goes over it, but will still queue songs from it if there's room.

**Comment by JMZ10** [comment]
you have misunderstood. this from the list being empty.

**Comment by MrBoombastic** [comment]
Idk if we talk about same thing, but in some cases bot will reply about 50 songs limit even if you set eg. 300 songs limit and this limit work. "50" is sometimes hardcoded in bot reply messages. I discovered it when I was working on my fork.
