### ISSUE TITLE
remove help

### ISSUE THREAD

**Issue by MeetPing** [DarkoPendragon/discord.js-musicbot-addon#106]
**Is your feature request related to a problem? Please describe.**no not really when i am using this on my bot i want to like not have the help command

**Describe the solution you'd like** a setting that allowes you to disable the help cmd

**Describe alternatives you've considered** to not use it

**Additional context** got none maybe like a helpcmd: "false" on 
```
client.music.start(client, {
  // Set the api key used for YouTube.
  // This is required to run the bot.
  youtubeKey: "YEET",
  helpcmd: "false"
 
});
``` 
Do that ^

**Comment by MeetPing** [comment]
@DarkoPendragon Hey this is a good suggestion, i suggest adding.

**Comment by trolhamonas** [comment]
You can already disable any command if you would like just follow the examples and change to the according command that you would like

**Comment by MeetPing** [comment]
@trolhamonas Can you give the code i got 
client.music.start(client, {
  // Set the api key used for YouTube.
  // This is required to run the bot.
  youtubeKey: "BLEEP",
  botPrefix: "$"
});

**Comment by trolhamonas** [comment]
help: {
    enable: false
}
Something like that, i havent tested it

**Comment by DarkoPendragon** [comment]
https://github.com/DarkoPendragon/discord.js-musicbot-addon#command-options
