### ISSUE TITLE
djRole must be a string

### ISSUE THREAD

**Issue by Esp8266-hax0r** [DarkoPendragon/discord.js-musicbot-addon#112]
**Describe the bug**
I am hosting a bot on Heroku and everything went good locally, but when i switched it to Heroku it shows me djRole must be a string, how can I fix it?

**Versions**
- OS/Env/Hosting Service - Heroku
- Module version discord.js-musicbot-addon-v2@1.10.4
- Discord.js version 11.5.1
- Node.js version 10.6

**Comment by DarkoPendragon** [comment]
I didn't make v2, I only made this one (the repo you're on). v2 is a fork someone made a year or so ago.
