### ISSUE TITLE
Bug in code: number instead of string

### ISSUE THREAD

**Issue by MrBoombastic** [DarkoPendragon/discord.js-musicbot-addon#116]
https://github.com/DarkoPendragon/discord.js-musicbot-addon/blob/71045c71ab0c2dedc40e971e1d7441995abf2426/index.js#L1459

"00000" should be string.

**Comment by DarkoPendragon** [comment]
It could be a string, but it can also be a number. It ends up the same either way for fetching or creating a new 'queue'.
