### ISSUE TITLE
Music glitches out at the end of every song

### ISSUE THREAD

**Issue by Lxk3y** [DarkoPendragon/discord.js-musicbot-addon#117]
**Describe the bug**
At the end of every song playing (using !play <songname>), it starts to sound like its lagging, the glitches out and just stops, bot leaves channel, and posts 

> :musical_note: | Playback finished~

**To Reproduce**
To reproduce this bug: Be in a voice channel and type !play <songname>. pick a song, listen to it and towards the end you will hear it starts to glitch out

**Expected behavior**
Song should continue to play like normal until the very end

**Screenshots**
N/A

**Versions**
- OS/Env/Hosting Service: Vultr VPS
- Module version: 13.8.1
- Discord.js version: 11.5.1
- Node.js version: 8.10.0

**Comment by Lxk3y** [comment]
Seems i forgot to install ytpl and ytsearcher which might be why? Works ok now

**Comment by canarado** [comment]
Could also have been a latency problem.

**Comment by NightcoreRYT** [comment]
This also happens sometimes in the latest version of the module. I think it just varies on how Discord's server status is.
