### ISSUE TITLE
Play command not queueing songs

### ISSUE THREAD

**Issue by Courbieee** [DarkoPendragon/discord.js-musicbot-addon#118]
**Describe the bug**
When I try and make the bot queue a song with the play command, it just overwrites the currently playing song
**To Reproduce**
To reproduce this bug:
All I am doing is this:
`play: {
                enabled: true,
                usage: '${prefix}play some tunes',
                help: "help text",
                alt: ["p", "pl"],
                exclude: false
}`

**Expected behavior**
I expected the bot to queue the song at the end of the queue

**Screenshots**
[http://prntscr.com/phyfxs](url)

**Versions**
- OS/Env/Hosting Service OS: Windows 10
- Module version: 13.8.1
- Discord.js version: 11.5.1
- Node.js version: 12.11.1

**Additional context**

**Comment by jylescoad-ward** [comment]
Can you give us a screenshot of the console?
