### ISSUE TITLE
Bot skip when trying to play some VEVO songs

### ISSUE THREAD

**Issue by Dirky14** [DarkoPendragon/discord.js-musicbot-addon#127]
**Describe the bug**
The bot skip some VEVO songs when i try to play these 

**To Reproduce**
To reproduce this bug:
Try to play some VEVO songs (exemple : Sigrid - Level Up (Live Performance) | Vevo by SigridVEVO)
**Expected behavior**
Play VEVO songs without problem

**Screenshots**

**Versions**
- OS/Env/Hosting Service Ubuntu 18.04
- Module version Last Version
- Discord.js version Last version
- Node.js version 12.8.1

**Comment by UnbreakCode** [comment]
same problem here

**Comment by DarkoPendragon** [comment]
This is due to copyright restrictions from YT. There's not much I can do but you can try using LavaLink instead. My module is lightweight but with less features, while LavaLink is a tad harder to setup but has more features and typically more stable.
