### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fydne** [DarkoPendragon/discord.js-musicbot-addon#128]
hi, maybe what I write later is connected with an error, but it gives me an error (I will attach a screenshot) + before that, when I wrote: Client, Music, from this type I got an error

**Comment by fydne** [comment]
![Desktop Screenshot 2019 12 06 - 22 40 08 90](https://user-images.githubusercontent.com/54745523/70343703-c5fca600-1879-11ea-8a9b-46e4de4ce96c.png)

**Comment by fydne** [comment]
![Desktop Screenshot 2019 12 06 - 22 47 19 12](https://user-images.githubusercontent.com/54745523/70344003-77034080-187a-11ea-93f3-ece71154739b.png)

**Comment by fydne** [comment]
/|\ error to <client>, <music>

**Comment by WilsontheWolf** [comment]
I'm sorry but this is very wrong. Nothing is wrapped in `<>` also it looks like your requiring `musicbot` and not `discord.js-musicbot-addon`. Learn some js

**Comment by fydne** [comment]
help

**Comment by WilsontheWolf** [comment]
Learn js

**Comment by fydne** [comment]
help!

**Comment by WilsontheWolf** [comment]
Useful links for learning JavaScript and Node:

codecademy online course: https://www.codecademy.com/learn/introduction-to-javascript
Eloquent Javascript, free book: http://eloquentjavascript.net/
Some Node:\nhttp://nodeschool.io/
https://www.codeschool.com/courses/real-time-web-with-node-js
discord.js getting started guides:
https://www.youtube.com/channel/UCvQubaJPD0D-PSokbd5DAiw/videos
https://www.youtube.com/channel/UCLun-hgcYUgNvCCj4sIa-jA/videos
Javascript reference/docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference
discord.js documentation: https://discord.js.org/#!/docs/

**Comment by fydne** [comment]
thanks

**Comment by fydne** [comment]
just now I understand how I was dumb, thanks
