### ISSUE TITLE
Music bot joins the leaves

### ISSUE THREAD

**Issue by mmcguire1** [DarkoPendragon/discord.js-musicbot-addon#129]
**Describe the bug**
When i play any song through the bot the bot will join and after 3 seconds it disconnects and says "Playback finished"

**To Reproduce**
Play anysone

**Expected behavior**
to play the song

**Screenshots**
https://img.mattomc.xyz/images/6wsoh.png

**Versions**
- OS: Ubuntu 19.04
- Module version: 13.8.1
- Discord.js version: 11.5.1
- Node.js version: 10.16.0

**Additional context**

**Comment by mmcguire1** [comment]
fixed it by reading previous error reports

**Comment by julien040** [comment]
Sorry if I reopen the Issue
Hi, my bot does the same thing. What changes have you made ?

**Comment by mattomc** [comment]
> Sorry if I reopen the Issue
> Hi, my bot does the same thing. What changes have you made ?

I believe I just did this command to remove the ffmpeg binaries
```
npm remove ffmpeg-binaries
```
