### ISSUE TITLE
Play command bug

### ISSUE THREAD

**Issue by NightcoreRYT** [DarkoPendragon/discord.js-musicbot-addon#132]
**Describe the bug**
I have the module working fine now. My only issue with it is the Play command. It searches for the song, joins the voice channel and then doesn't do anything. I typed >queue to get the songs in the queue and it said there wasn't any. 

**To Reproduce**
To reproduce this bug: >play songname | URL and watch. It joins the voice channel but doesn't play the song. 

**Expected behavior**
The expected behavior should've been the bot playing the music

**Screenshots**
![image](https://user-images.githubusercontent.com/31454793/72652883-80ef8780-3980-11ea-9df2-ab99a5cb4a7a.png)
![image](https://user-images.githubusercontent.com/31454793/72652889-8947c280-3980-11ea-8b11-11e61c75e9e4.png)
![image](https://user-images.githubusercontent.com/31454793/72652907-9664b180-3980-11ea-8a4b-e66850db474d.png)

**Versions**
- Glitch
- Module version: Latest
- Discord.js version: Latest
- Node.js version: Latest

**Additional context**

**Comment by davkms** [comment]
I have the same issue, it joins a channel and leaves after a short delay.
Tried updating all packages thats connected to it, no luck.

**Comment by favianrizqulloh** [comment]
@davkms same issue.

Any updates?

**Comment by NightcoreRYT** [comment]
@davkms @favianrizqulloh I've made a fix. Until Darko updates his module, replace `discord.js-musicbot-addon` with `discord.js-musicbot-v2`
