### ISSUE TITLE
cannot read module

### ISSUE THREAD

**Issue by pranav2206** [DarkoPendragon/discord.js-musicbot-addon#134]
throw err;
    ^

Error: Cannot find module 'm3u8stream/lib/parse-time'
Require stack:
- C:\Users\Avyaan\Desktop\music bot\node_modules\discord.js-musicbot-addon\node_modules\ytdl-core\lib\info-extras.js
- C:\Users\Avyaan\Desktop\music bot\node_modules\discord.js-musicbot-addon\node_modules\ytdl-core\lib\info.js
- C:\Users\Avyaan\Desktop\music bot\node_modules\discord.js-musicbot-addon\node_modules\ytdl-core\lib\index.js
- C:\Users\Avyaan\Desktop\music bot\node_modules\discord.js-musicbot-addon\index.js
- C:\Users\Avyaan\Desktop\music bot\index.js
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:852:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:74:18)?[39m
    at Object.<anonymous> (C:\Users\Avyaan\Desktop\music bot\node_modules\?[4mdiscord.js-musicbot-addon?[24m\node_modules\?[4mytdl-core?[24m\lib\info-extras.js:5:21)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:852:19)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [
    ?[32m'C:\\Users\\Avyaan\\Desktop\\music bot\\node_modules\\discord.js-musicbot-addon\\node_modules\\ytdl-core\\lib\\info-extras.js'?[39m,
    ?[32m'C:\\Users\\Avyaan\\Desktop\\music bot\\node_modules\\discord.js-musicbot-addon\\node_modules\\ytdl-core\\lib\\info.js'?[39m,
    ?[32m'C:\\Users\\Avyaan\\Desktop\\music bot\\node_modules\\discord.js-musicbot-addon\\node_modules\\ytdl-core\\lib\\index.js'?[39m,
    ?[32m'C:\\Users\\Avyaan\\Desktop\\music bot\\node_modules\\discord.js-musicbot-addon\\index.js'?[39m,
    ?[32m'C:\\Users\\Avyaan\\Desktop\\music bot\\index.js'?[39m
  ]
}

**Comment by DarkoPendragon** [comment]
You can try installing it manually with npm (`npm install parse-time`), do `cp -r ./node_modules/m3u8stream/dist ./node_modules/m3u8stream/lib` in your console within your working directory, or manually change the files: 
![image](https://user-images.githubusercontent.com/28911975/73087025-c986d380-3e9f-11ea-83c3-d89acb930ab9.png)
