### ISSUE TITLE
leave and clear Cmd don't work

### ISSUE THREAD

**Issue by theusualthing** [DarkoPendragon/discord.js-musicbot-addon#18]
When I call any of these commands to clear the queue or stop the bot, it gives me error and the bot needs restarting.

clearCmd: 
![image](https://user-images.githubusercontent.com/16181314/35484127-ea7ee96e-044b-11e8-96ac-f0545e3b0045.png)

LeaveCmd:
![image](https://user-images.githubusercontent.com/16181314/35484139-24bb3704-044c-11e8-8527-ce3ca65ba0bd.png)

**Comment by DarkoPendragon** [comment]
I nor anyone else I know using the model got these errors. What version are you using? (it's printed in the console for handy reference)
Also;
Clear command:
![clear command](https://user-images.githubusercontent.com/28911975/35489572-4b2beafe-0466-11e8-883e-8a230b79c954.png)

Others that change loops:
![other loops](https://user-images.githubusercontent.com/28911975/35489583-65324560-0466-11e8-9676-f89a4b0e9b01.png)

**Comment by theusualthing** [comment]
The addon is 1.9.0
Node is 8.9.4

**Comment by DarkoPendragon** [comment]
Currently unless you rewrite the code, you can't. Those are somethings I was going to add next though.
