### ISSUE TITLE
Bot crashed after playing a song.

### ISSUE THREAD

**Issue by ThePjpollie** [DarkoPendragon/discord.js-musicbot-addon#19]
Whenever I request a song through `!play` (with search feature or link) it crashes the bot.
It does provide me 8 songs to choose from first, I select the right song. The bot joins the voicechannel and in the textchannel it says: `🎵 | Queued Don Diablo & Steve Aoki x Lush & Simon - What We Started ft. BullySongs (Official Music Video)` (so I think it fails when starting to play the song)

__Error:__
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at PassThrough.Writable.write (_stream_writable.js:288:21)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at emitThree (events.js:141:20)
    at DestroyableTransform.emit (events.js:217:7)
    at emitThree (events.js:136:13)
    at FfmpegCommand.emit (events.js:217:7)
    at emitEnd (D:\Projects\Freetime\Discord Bots\AA Projects\MusicMaistro_New\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at D:\Projects\Freetime\Discord Bots\AA Projects\MusicMaistro_New\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at D:\Projects\Freetime\Discord Bots\AA Projects\MusicMaistro_New\node_modules\async\dist\async.js:473:16
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by DarkoPendragon** [comment]
Well, firstly, the bot is supposed to give no more or less than 10 songs currently. Not sure how you're getting 8 unless you changed something.

That error should be long gone too. It's a problem relating to ffmpeg. Newer versions (1.5+) use ffmpeg installed, while lower versions use the ffmpeg-binaries model. With the latest version you shouldn't get that error unless you don't have ffmpeg installed/exported right.
