### ISSUE TITLE
Features: commandCooldown & disablePlaylists & maxPerUser

### ISSUE THREAD

**Issue by JMGbaum** [DarkoPendragon/discord.js-musicbot-addon#25]
1.) Make a commandCooldown option so each user can only do a music command every X seconds so that people can't spam songs.

2.) Make an option to disable playlists so people can't fill up the queue.

3.) Maybe, if possible, add an options to have a max amount requested by one user in the playlist at any given time. (So if the max queue size is 20, you can set the maxPerUser to 5 so that each person can only have 5 of their songs in the queue at any time)

**Comment by DarkoPendragon** [comment]
Looking at the issues, since I rarely do, I realize I forgot about this.
Will be added in v13.x.
