### ISSUE TITLE
Unexpended token function

### ISSUE THREAD

**Issue by boldizsarf** [DarkoPendragon/discord.js-musicbot-addon#28]
Hi! 
I just installed this addon (thanks for made this, because i can't write a music service).
But i have a porblem: http://prntscr.com/imfwma

**Comment by DarkoPendragon** [comment]
Check your version of Node. The bot requires 8.4+. That's the only reason I now for that error.

**Comment by DarkoPendragon** [comment]
_Closed due to inactivity/lack of intrest._
