### ISSUE TITLE
How can i fix this :(

### ISSUE THREAD

**Issue by ko11380** [DarkoPendragon/discord.js-musicbot-addon#41]
**Describe the bug**
if i adding music or use different commend
occurs error in node.js

Error: Dispatcher SetLast: no server queue
    at musicbot.setLast.then.catch (C:\Users\user\node_modules\discord.js-musicbot-addon\index.js:2142:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Screenshots**

**Versions**
windows10 pro
Discord.js Version : 11.3.2
Node.js version : 8.11.2

![k-003](https://user-images.githubusercontent.com/39909328/40917018-c51ac90e-683c-11e8-9493-2d92b32242bc.png)

**Comment by DarkoPendragon** [comment]
This should only occur when something is passed to the `setLast` function and it doesn't have a queue for the server ID passed. Have you changed anything or using the function export?

**Comment by ko11380** [comment]
no :(

Music.start(client, {
    youtubeKey: 'AIzaSyAP9NP5b34R21cHcweBwJxtaSxsd',
    botAdmins: ["2813430xxxx1xx78x4"],
    enableQueueStat:true,
    prefix: settings.prefix, // Prefix for the commands.
    global: true,            // Non-server-specific queues.
    maxQueueSize: 200,        // Maximum queue size of 25.
    clearInvoker: true,      // If permissions applicable, allow the bot to delete the messages that invoke it.
  });

**Comment by DarkoPendragon** [comment]
Have you tried disabling global queues? It might cause it. I honestly never even thought to test it with the global queue.

**Comment by ko11380** [comment]
# A new error occurs.

(node:1604) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at item.request.gen.end (C:\Users\free4\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
    at then (C:\Users\free4\node_modules\snekfetch\src\index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DarkoPendragon** [comment]
That might be due to delete invoker (`clearInvoker`) being true, it might not "see" the message or I messed something up somewhere.

**Comment by DarkoPendragon** [comment]
Try using [this testing version](https://github.com/DarkoPendragon/discord.js-musicbot-addon/blob/testing-branch/index.js) and see if it fixes the errors caused by either of those settings being on for you.

**Comment by ko11380** [comment]
testing version is not occuer error lol
thank's for your help

**Comment by ko11380** [comment]
if i used skip commend it occuer

**Comment by ko11380** [comment]
yea

**Comment by DarkoPendragon** [comment]
Are you still using global queues when this happens?

**Comment by ko11380** [comment]
no, i m not use global

**Comment by alexzhivil** [comment]
1. There's an error in the deceleration of the isQueueEmpty promise.
Instead of checking for "queue.songs.length", it checks for "queue.length", fix that (around :1135).
2. Around :2110, before the promise that plays the next song, check that the queue is not empty. Add something like
    if(queue.songs.length <= 0)
        return;

I've done that and now it all works perfectly. 
No errors. 
Bot quits channel when it ends playing. 
Music doesn't get stuck any more.
