### ISSUE TITLE
prefix set

### ISSUE THREAD

**Issue by mu3106** [DarkoPendragon/discord.js-musicbot-addon#43]
custom prefix set no work

**Comment by DarkoPendragon** [comment]
Okay, I'll be flat out honest. This is a horrible issue.
Anyways, moving on. What are you trying to set the prefix to?

**Comment by mu3106** [comment]
Im trying to do t!set prefix r

**Comment by DarkoPendragon** [comment]
Do you have `advancedMode` and related options enabled and set?

**Comment by mu3106** [comment]
How do I do that?
