### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by mu3106** [DarkoPendragon/discord.js-musicbot-addon#45]
Okay so when I for example do t!set prefix m! it sets it for the current session, but then it reverts to the old prefix t! when i restart the bot. Fix?

**Comment by DarkoPendragon** [comment]
It's not a bug, so there's nothing to fix. The storage for the music bot isn't permanent. So when you restart, it starts off with the data you set upon doing `Music.start(client, {options})`. You can always Write something to change the prefix using the export to match current prefixes of your bot however.
