### ISSUE TITLE
Bot crashed when requesting music

### ISSUE THREAD

**Issue by jylescoad-ward** [DarkoPendragon/discord.js-musicbot-addon#46]
When I request a song it just says searching then the bot crashes

Here is the music part of the code
>Music.start(client, {
>  prefix: 's!m', // Prefix for the commands.
>  global: true,            // Non-server-specific queues.
>  maxQueueSize: 255,        // Maximum queue size of 25.
>  clearInvoker: true,      // If permissions applicable, allow the bot to delete the messages that invoke it.
>  helpCmd: 'help',        // Sets the name for the help command.
>  playCmd: 'play',        // Sets the name for the 'play' command.
>  volumeCmd: 'vol',     // Sets the name for the 'volume' command.
>  leaveCmd: 'leave',      // Sets the name for the 'leave' command.
>  enableQueueStat: true,
>  youtubeKey: config.ytapi,
>});

Here is what the console spat out when it crashed
>------- SeedBot -------
> Version: 12.0.6
> Extra Logging: false.
> Using Global Queue: true.
> Node.js Version: v8.11.3
------- SeedBot -------
(node:9292) UnhandledPromiseRejectionWarning: Error code: 400
(node:9292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And here the modules that I have imported

>// Load up the discord.js library
>const Discord = require("discord.js");
>
>//custom modules
>const Music = require('discord.js-musicbot-addon');
>const ffmpeg = require('@ffmpeg-installer/ffmpeg');
>console.log(ffmpeg.path, ffmpeg.version);

**Comment by DarkoPendragon** [comment]
Global and ClearInvoker are known to cause issues. There are also unresolved issues I know about and plan to fix, I'll be working on the module _heavily_ during the summer (next month and so on-ish) and they'll be resolved.

Also, ffmpeg should just be in your PATH/ENV, you shouldn't/have no need to import it.

**Comment by jylescoad-ward** [comment]
ffmpeg is in my path/env, but it still dosent work :/
