### ISSUE TITLE
Crashes on Search and Play

### ISSUE THREAD

**Issue by n3oney** [DarkoPendragon/discord.js-musicbot-addon#50]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
2018-06-25T06:25:24.821018+00:00 app[worker.1]:     at exports.determineType.type (/app/node_modules/ytsearcher/lib/deps/determineType.js:11:57)

Help

**Comment by jylescoad-ward** [comment]
Getting the same problem :/

**Comment by hdclandiscord** [comment]
i got same problem

**Comment by DarkoPendragon** [comment]
I apologize for the inconvenience, but I haven't been working on the module for issues regarding my health. I am aware of current errors that are causing the bot to crash and once I'm in better health I'll have them sorted out (I've said this in the Discord server previously as well).

**Comment by etstringy** [comment]
Temp Fix: 
1 open up the index.js file in project_folder\node_modules\discord.js-musicbot-addon
2 find the code snippet `type : video`
3 comment this line out so it looks like this
`musicbot.searcher.search(searchstring
            // , {type: 'video'}
            )`

this will disable video selection but the audio works at least

4 save and run

**Comment by hdclandiscord** [comment]
i am using glitch for that.


2018-07-03 2:42 GMT+07:00 etstringy <notifications@github.com>:
