### ISSUE TITLE
Null error on leave

### ISSUE THREAD

**Issue by Banshee786** [DarkoPendragon/discord.js-musicbot-addon#54]
I get this error:
```
Bot > TypeError: Cannot read property 'player' of null
Bot >     at Timeout.setTimeout [as _onTimeout] (/home/usr/code/Discord_bot/node_modules/discord.js-musicbot-addon/index.js:1891:17)
Bot >     at ontimeout (timers.js:498:11)
Bot >     at tryOnTimeout (timers.js:323:5)
Bot >     at Timer.listOnTimeout (timers.js:290:5)
```

This happens when i use the leave command when the bot is playing music.

os:Ubuntu18.04
module version: 12.0.6
Discord,js version:11.3.2
Node.js version: 8.11.3

**Comment by fire-stone** [comment]
So this issue is still around 2 month after. Is it getting fixed or how is the status to this problem?
