### ISSUE TITLE
Loop Bug + Feature Request

### ISSUE THREAD

**Issue by miramallows** [DarkoPendragon/discord.js-musicbot-addon#60]
**Is your feature request related to a problem? Please describe.**
Yeah, basically if you type the `loop` command 3 or more times, afterwards it'll just keep saying that loop is disabled.

**Describe the solution you'd like**
change the command to this.
`loop all` - loops all of the queue.
`loop one` - loops one.
`loop off` - turns off loop.

**Describe alternatives you've considered**
maybe after the 3rd answer of how loop is disabled, make loop enable for 1 single song at 4th time and 5th be loop all, then 6th be loop disabled again. idk if you get what i mean

**Comment by RazorApple** [comment]
^ Same issue. Atleast make the bot loop the cmd so you can do <prefix>leave infinte times.
