### ISSUE TITLE
TypeError: Music is not a constructor

### ISSUE THREAD

**Issue by Airrocket** [DarkoPendragon/discord.js-musicbot-addon#64]
When I try to run the example code in release 1.6 I get the error `TypeError: Music is not a constructor` on the line `const music = new Music(bot, {`. I have made sure to install the discord.js-musicbot-addon package with npm, and I declare const Music right above the line that declares const music.

I've tried copying the code from advancedMusicBot.js into my code, I got the error, and I have tried running basicMusicBot.js with the same error. I haven't made any changes to the code.

Version 11.4.2 of Discord.js
Version 8.11.4 of Node.js

**Comment by canarado** [comment]
Try doing `npm install discord.js-musicbot-addon@latest`

**Comment by Airrocket** [comment]
It didn't seem to change anything. Do I have to uninstall the older version if I have one?

**Comment by DarkoPendragon** [comment]
That hasn't been the way to start the module for quite some time. 1.6 is also a very old version and I don't recommend using it. If you've done `npm install discord.js-musicbot-addon` then you should be using version 13. Here's how you start the module:
```js
Music.start(client, {
    youtubeKey: ""
});
```
