### ISSUE TITLE
TypeError: Cannot read property 'voiceChannel' of undefined

### ISSUE THREAD

**Issue by Airrocket** [DarkoPendragon/discord.js-musicbot-addon#66]
Sorry for opening another issue report, but I keep getting an error while using version 13.0.1 of the library installed using npm, and I'm using the examples from version 13. I've also made sure to use the command I was given to start the module in my last issue report.

I've gotten to the point of getting my bot into my server, but when I do the play command, the bot crashes and I get an error saying:
```
 if (msg.member.voiceChannel === undefined) return msg.channel.send(musicbot.note('fail', `You're not in a voice channel.`));
                   ^

TypeError: Cannot read property 'voiceChannel' of undefined
    at Music.musicbot.playFunction (C:\Users\Eric\node_modules\discord.js-musicbot-addon\index.js:316:20)
```
I have made sure that I am in a voice channel.
Here is my code, it is using the exmaple from version 13 of bot_basic.js, and to execute the command I'm using the example command from version 13 of callingCommand.js:
```
class Bot extends Discord.Client {
  constructor(options) {
    super(options);
    this.music = require("discord.js-musicbot-addon");
  }
}

const client = new Bot();

let ytapikeyRawdata = fs.readFileSync("ytapikey.json");
let ytapikey = JSON.parse(authRawdata);


else if(command == "PLAY") {
      client.music.bot.playFunction(args, message);
    }
```
All of my code can be found here: https://pastebin.com/UfsBNR0H

**Versions**
- Version 11.4.2 of Discord.js
- Version 8.11.4 of Node.js
- Version 13.0.1 of discord.js-musicbot-addon

Thanks for taking the time to go throught this, any help is greatly appreciated!

**Comment by mcao** [comment]
> Version 5.6.0 of Discord.js

I highly doubt that

**Comment by Airrocket** [comment]
I did npm discord.js -v and that's what I got. If there is some other way to check it please let me know.

**Comment by Airrocket** [comment]
I just updated it to 11.4.2.

**Comment by mcao** [comment]
> npm discord.js -v

That checks the version of `npm`, not discord.js. Check discord.js by doing `require('discord.js').version`

**Comment by DarkoPendragon** [comment]
You're using the `.playFunction()` function wrong. Here's how it should be done:
```js
if (command == "PLAY") {
    client.music.bot.playFunction(<Message>, <Suffix>);
}
```
You pass the message object first, then the suffix. The suffix should be a string with what the search query is, aka `Scandriod - Salvation Code` and not an object/array.
