### ISSUE TITLE
Ability for the bot to display what song is being played

### ISSUE THREAD

**Issue by Huskydog9988** [DarkoPendragon/discord.js-musicbot-addon#69]
**Is your feature request related to a problem? Please describe.**
I've found it annoying to not know what song the bot is currently play. An example of this is the fact that the bot in no way says what song is currently being played without using a command.

**Describe the solution you'd like**
The solution I would like is to this is to have the bot display the current song via a user presence. An example would be the picture below.
![image](https://user-images.githubusercontent.com/39809509/48305061-09a7a380-e4f2-11e8-9f2f-50744c41cc33.png)

**Describe alternatives you've considered**
An alternate solution to the problem is to have the bot send a message in the same channel that the bots commands are being sent in. For example the bot could say "🎶 | Now playing (song would go here).".

**Additional context**
Simple code to have the bot have the presence as "listening to". The only thing that would need changing is the "name" value.
![image](https://user-images.githubusercontent.com/39809509/48305165-c51d0780-e4f3-11e8-8e53-248e1dacfd16.png)

**Comment by DarkoPendragon** [comment]
There's a now playing command (np). The old bot messaged the channel when a new song started playing, but it seemed spammy. I can re-add that as an optional feature however. And showing the playing song through a game presence has problems if its not just on one server, and it won't update very quickly either for short videos, due to rate limiting.

**Comment by Huskydog9988** [comment]
Ik that the bot would have problems if the bot is playing music on multiple server, the way to combat this is to only have this on if the bot has the global playlist on, and the feature is also on.

**Comment by DarkoPendragon** [comment]
Global playlists were removed due to causing too many problems. I'll still add the feature though.

**Comment by Huskydog9988** [comment]
May i ask how they where causing problems?
