### ISSUE TITLE
Status Changing Configuration

### ISSUE THREAD

**Issue by miramallows** [DarkoPendragon/discord.js-musicbot-addon#71]
**Is your feature request related to a problem? Please describe.**
My bot already has a fixed status that works, I don't want it to show the song as a status.

**Describe the solution you'd like**
disablestatus config

**Comment by DarkoPendragon** [comment]
There were a few option issues. It should have been disabled by default (option is `musicePresence`, Boolean). Going through it there were also Promise errors as I poorly handled them. This should be fixed in the new update.

**Comment by miramallows** [comment]
one more question as i dont wanna re-open a new issue.

how do i disable the help command? adding this code didn't help
```
  help: {
    disabled: true
  }
```
i also tried the following:
```
disableHelp: true
```
