### ISSUE TITLE
Not sure how to disable help.

### ISSUE THREAD

**Issue by miramallows** [DarkoPendragon/discord.js-musicbot-addon#72]
one more question

how do i disable the help command? adding this code didn't help
```
  help: {
    disabled: true
  }
```
i also tried the following:
```
disableHelp: true
```

**Comment by DarkoPendragon** [comment]
```js
  help: {
    enabled: false
  }
```
As per:
![image](https://user-images.githubusercontent.com/28911975/48952774-699a4300-ef11-11e8-9ba6-6af46fd9db8d.png)
