### ISSUE TITLE
Logging option default value

### ISSUE THREAD

**Issue by TheSacredPixel** [DarkoPendragon/discord.js-musicbot-addon#73]
How come the `logging` option is set to `true` by default?  I feel that if it only caught unhandled errors and the like then this would be understandable, but considering it logs even minor things like the now playing song embeds (which take up *a lot* of space in the console), it seems too verbose by default.

**Comment by DarkoPendragon** [comment]
It shouldn't have been logging that, I had it there for testing from quite awhile back but apparently forgot to remove it. Its now been removed so it's less spamy.
