### ISSUE TITLE
Anyone can change volume

### ISSUE THREAD

**Issue by jylescoad-ward** [DarkoPendragon/discord.js-musicbot-addon#77]
Whenever I set the setting `defVolume` to `true` it still allows anyone to set the volume.

**Comment by DarkoPendragon** [comment]
The correct option is `anyoneCanAdjust`. `defVolume` is an integer from 1 to 200 for the default volume output of the stream, per queue. `anyoneCanAdjust` is a Boolean that states whether or not anyone can change the volume of the queue/the bots output.

**Comment by jylescoad-ward** [comment]
Thats what i meant `anyoneCanAdjust`
