### ISSUE TITLE
Support Discord.js-commando

### ISSUE THREAD

**Issue by fire-stone** [DarkoPendragon/discord.js-musicbot-addon#79]
**Is your feature request related to a problem? Please describe.**
I like discord.js but i think discord.js-commando is much simpler and also a lot cleaner. I tried your addon before and I personally think it's a great package.

**Describe the solution you'd like**
The solution is very simple (not the coding part obv.) it only has to support Discord.js-commando.

**Additional context**
The weird part for me is that the bot start's but you can't play something with the bot. So in the console it looks like it works just fine.

Again I really like your Project/Package and I would like to see you succeed with that project (^_^)

Here is the link to the Site: [Discord.js-commando](https://archomeda.github.io/discord.js-commando-plus/#/)

**Comment by DarkoPendragon** [comment]
Commando is easy because its essentially wrapping Discord.js and adding in functions you'd normally code yourself in your own way. Good idea, but if I were to do this I'd make a different module entirely.
