### ISSUE TITLE
Create a varible for np

### ISSUE THREAD

**Issue by WilsontheWolf** [DarkoPendragon/discord.js-musicbot-addon#80]
**Is your feature request related to a problem? Please describe.**
I would like it if the bot had the option of saving the NP song to some varible (that has each server so there could be different ones, so the user could acess it. this would be nice for if your bot is in several servers or you want to customize the NP presence. This would allow the user to have an unlimited amount of options for what the could do.

**Describe the solution you'd like**
Some kind of ability to acces the nowplaying for a server using something like Music.serverId.nowPlaying so we could access it easily.

**Describe alternatives you've considered**
Saving the np into some external file like an sqlite or json.
**Additional context**
It could be useful for things like:
<img src=https://i.gyazo.com/bf913412ed8607637bf78edb6f683846.png>
<img src=https://i.gyazo.com/80ed810087c51024c221ae5f1286bb65.png>
<img src=https://i.gyazo.com/0e592e07521dbd9919dd36a2bd23e859.png>

**Comment by canarado** [comment]
Running one instance of the bot would not allow you to set multiple presences. That would require sharding.

**Comment by WilsontheWolf** [comment]
the point of that one was to have the help command there as well

**Comment by DarkoPendragon** [comment]
Technically, the queue object per server has a `last` object as well. This could serve as the now playing since its updated every time a different song is played that does not equal the current last or the loop isn't set to song, aka single looping.

**Comment by WilsontheWolf** [comment]
I'm not sure how to do that

**Comment by WilsontheWolf** [comment]
I just though that mabey we could save it as a js varible using something like the 
```javascript
nowplayingstorage: {
    //  the server ID and varible name would go below
    serverID: "Variblename",
    // Like this
    405095053636141056: mySever,
   // would suport as many as you like
    517792662703570954: cool
   //etc
  },
```

**Comment by DarkoPendragon** [comment]
The only reason bot wouldn't be defined is if you didn't somewhere put the music object into the client, such as:
```js
client.music = require("discord.js-musicbot-addon");
```
or a different way, such as making a class off of the Discord Client and inserting it into it.
