### ISSUE TITLE
Bot is searching for song twice

### ISSUE THREAD

**Issue by MrBoombastic** [DarkoPendragon/discord.js-musicbot-addon#81]
When I want to play song, bot sends message twice.

My code:
```js
const Discord = require('discord.js');
const client = new Discord.Client();
client.music = require("discord.js-musicbot-addon");
client.music.start(client, {
    youtubeKey: "token",
    play: {
        usage: "{{prefix}}play some tunes",
        exclude: false
    },
    anyoneCanSkip: true,
    ownerOverMember: true,
    ownerID: "363365720295473154",
    cooldown: {
        enabled: false
    }
});
client.on("message", (msg) => {
    if (msg.author.bot) return;
    const client = msg.client;
    let prefix = "!"
    const command = msg.content.slice(prefix.length).split(/[ \n]/)[0].trim();
    const suffix = msg.content.slice(prefix.length + command.length).trim();
    if (msg.content.startsWith(prefix) && command == "play") {
        client.music.bot.playFunction(msg, suffix);
    };
});
client.login("token");
```
It should respond only once.

![screenshot](https://user-images.githubusercontent.com/18630357/50515989-5e09e100-0aa8-11e9-8a90-c085ecb183db.png)

- OS/Env/Hosting Service - Windows 7
- Module version - 13.4.0
- Discord.js version - 11.4.2
- Node.js version - 10.9.0

**Comment by DarkoPendragon** [comment]
Its searching twice since you're adding an extra command in a message event to listen for when someone does `play song`, while the module is already doing the same. Either disable the play command in the module or remove it from the message event.
