### ISSUE TITLE
sound quality is bad

### ISSUE THREAD

**Issue by fish0373** [DarkoPendragon/discord.js-musicbot-addon#86]
Sometimes, I use mobile to listen music, the music bot sound quality is very bad.
I try to add dispatcher option 'bitrate: 48000', then it's better.
Maybe can update that, thanks.

**Comment by arrudagates** [comment]
hey, how do you add that option?

**Comment by fish0373** [comment]
you can find this dispatcher in function "musicbot.executeQueue"

VoiceConnection -> https://discord.js.org/#/docs/main/stable/class/VoiceConnection
StreamOptions -> https://discord.js.org/#/docs/main/stable/typedef/StreamOptions

put bitrate:48000 in this Object
![default](https://user-images.githubusercontent.com/22660527/51959942-b3635480-2491-11e9-83ce-8f02981a0bb4.png)

**Comment by DarkoPendragon** [comment]
Setting the bitrate has now been added as of 13.4.3.
