### ISSUE TITLE
Volume command

### ISSUE THREAD

**Issue by Anish-Shobith** [DarkoPendragon/discord.js-musicbot-addon#88]
Today when i was about to play a music i by mistakly typed volumr instead of play so i found that the volume command does not check if the inputed argument is a number or not!!

Maybe using `isNaN()` to check if entered args is a number or not!!

And it would accept the command even if its a text but in the mesaage it would give a message saying volume changed to NaN%

**Comment by DarkoPendragon** [comment]
Added in version 13.4.4.
