### ISSUE TITLE
Issues with Queuing system

### ISSUE THREAD

**Issue by Anish-Shobith** [DarkoPendragon/discord.js-musicbot-addon#89]
Some of the songs gets skipped in the queue... example : 1 song is playing i add 2 more songs it will not play the next song it would skip to the last song !!

**Comment by canarado** [comment]
This is most likely the YouTube API not allowing the streaming of a region or age limited video. The module that actually streams the data from youtube does not allow this type of content. This is not a problem with the Darko's music module.

**Comment by mobilegaming08** [comment]
I had the same issue and those video I played aren't claimed or age restricted. I even tried others and same issue with npm version. I'll see if I can proof with a video so you guys will get what we mean.

**Comment by Anish-Shobith** [comment]
It does it everytime but 🤔

**Comment by DarkoPendragon** [comment]
Like canarado said, this isn't a problem on my end. It's either YouTube's API or ytdl at fault. I can't fix something that I didn't break.

**Comment by LarmuseauNiels** [comment]
I had a similar issue where after the first song in the queue finishes it would start playing the third song in the queue bud would still show the previous song in the queue commands output. I managed to temp fix it by removing a '+ 1' on line 1246 in the executeQueue function. Bud I think it might be caused by the queue shift dispatcher running to early?

**Comment by arrudagates** [comment]
It always happens with any song, and sometimes it happens with songs that played before and we are trying to play again, same video, different results.

**Comment by arrudagates** [comment]
as @LarmuseauNiels stated, that also fixed for me, but instead of just removing the "+ 1" from line 1246 i also had to remove it from line 1251, proving that this is, in fact, a bug on this module.
Can we reopen this issue?
