### ISSUE TITLE
Bot joins, but then leaves

### ISSUE THREAD

**Issue by MrBoombastic** [DarkoPendragon/discord.js-musicbot-addon#92]
**Describe the bug**
Bot joins, but soon after that leaves. No errors in console.

**To Reproduce**
To reproduce this bug:
```js
class BOT extends Client {
  constructor(options) {
    super(options);
    this.config = require("./config.js");
    this.Discord = require("discord.js")
    this.commands = new Collection();
    this.aliases = new Collection();
    this.music = require("discord.js-musicbot-addon");
    this.music.start(this, {
      youtubeKey: this.config.ytkey,
      anyoneCanSkip: true,
      ownerOverMember: true,
      ownerID: this.config.ownerID,
      botPrefix: "===",
    });
  }
```
Like in Guidebot-Class.
**Expected behavior**
It should just work.

**Versions**
- Ubuntu 16.04 LTS
- Module version: 13.4.4
- Discord.js version: 11.4.2
- Node.js version: 10.15.3

**Additional context**
FFmpeg: v2.8.15

**Comment by MrBoombastic** [comment]
Fixed!
```
npm remove ffmpeg-binaries
```
I don't know what installed it, but when I( removed it, it just works!

**Comment by arrudagates** [comment]
Close the issue, then
