### ISSUE TITLE
Fix for queue skipping issue

### ISSUE THREAD

**Issue by arrudagates** [DarkoPendragon/discord.js-musicbot-addon#93]
Removing the "+1" from line 1251 fixes the bug that skips songs from the queue, proving that this is, in fact, a bug on this module and with a really easy fix, I am running a fork just for that 2 character change.

**Comment by arrudagates** [comment]
Hey, why are you closing the issue?

**Comment by DarkoPendragon** [comment]
As of [13.5.0](https://github.com/DarkoPendragon/discord.js-musicbot-addon/blob/master/changelog.md#1350) that's been fixed.
