### ISSUE TITLE
The music stops 15 seconds before the end

### ISSUE THREAD

**Issue by Nicolazon** [DarkoPendragon/discord.js-musicbot-addon#95]
**Describe the bug**
The music stops 15 seconds before the end and move on to the next.

**Versions**
- OS/Env/Hosting Service : Debian 8
- Module version : 13.5.1
- Node.js version : 8.15.1

**Comment by MrBoombastic** [comment]
Maybe update Node.JS to newest LTS.

**Comment by mobilegaming08** [comment]
I did encounter this but only occur for me if it's the last song playing in queue or just one song playing. I'm using the latest Node.JS version and lastest module btw so yeah.

**Comment by Millie290** [comment]
Same for me so idk why maybe the os can affect on arch no problems but with debian well it stop before so ...

**Comment by mobilegaming08** [comment]
I mean I use Glitch which it uses, if not based on, ubuntu if I'm not mistaken. I think it has something to either do with ytdl-core or discord.js voice like to do like leave a bit early.

**Comment by recreationx** [comment]
this issue happened to me too, ran it on Glitch and it always stops abit early

**Comment by MeetPing** [comment]
yeah it always stops a bit early
i always tried it on my own bot and it sure does end early

**Comment by DarkoPendragon** [comment]
I've honestly tried fixing this, but since I've never been able to reproduce this on my end I've mostly given up. This issue will be closed for now.

**Comment by CyaOnDaNet** [comment]
Anyone figure this out, right now my bot is ending songs about 30-45 seconds before the actual song ends and its extremely frustrating.
