### ISSUE TITLE
bot connects but nothing plays when requesting song

### ISSUE THREAD

**Issue by mmcguire1** [DarkoPendragon/discord.js-musicbot-addon#99]
**Describe the bug**
whenever I want to listen to music and after I do the command !play (URL) it joins the channel but no music plays. it comes back with a error in the console. whenever I try to do it in my windows 10 test environment (my desktop) it works perfectly. I am using a Ubuntu 19.04 VPS from Linode

**To Reproduce**
To reproduce this bug I need to do the command !play (URL) and it comes up with the same issue

**Expected behavior**
The bot to start playing the song that I asked it to play.

**Screenshots**
![image](https://user-images.githubusercontent.com/25604855/57054396-88c4aa00-6cd3-11e9-98dc-15a88ac47c6f.png)

**Versions**
- OS: Ubuntu 19.04
- MODULE: 13.4.5
- Discord.JS: 11.4.2
- Node.js: 12.10.0

**Additional context**

**Comment by DarkoPendragon** [comment]
This isn't caused by the module (as far as I can tell). It's a problem with node-gyp/python/build tools on your end.
